stages:
    - test

# From https://docs.gitlab.com/ee/ci/merge_request_pipelines/#excluding-certain-jobs
.only-default: &only-default
  only:
    # only: [branches, tags] is the default
    # extend it by merge_reguests
    # and limit branches to master and release/*
    # See also: https://docs.gitlab.com/ee/ci/yaml/#onlyexcept-basic
    - master
    - /^release/.*$
    - tags
    - merge_requests

test pyln-manager:
  <<: *only-default
  stage: test
  tags:
    - Agile_GUI_Docker
  script:
    - pip2 install --user --upgrade pytest
    - pip2 install pytest-runner==5.2  # this is py2 compatible, ver 5.3 is not
    - pip2 install --user --upgrade pyyaml
    - xvfb-run -as "-screen 0 1920x1200x24" python2 setup.py pytest --addopts '-vx -m "(core or gui) and not unstable and not user_input"'

