from state_properties import StatePropertiesView  # old
from container_state import ContainerStateView  # old
from single_widget_window import SingleWidgetWindowView

from graphical_editor import GraphicalEditorView
from state_data_port_editor import StateDataportEditorView

from input_port_list import InputPortsListView
from output_port_list import OutputPortsListView
from scoped_variables_list import ScopedVariablesListView
from global_variable_editor import GlobalVariableEditorView
from state_overview import StateOverviewView
from state_outcomes import StateOutcomesTreeView
from state_outcomes import StateOutcomesEditorView
from source_editor import SourceEditorView
from connections_editor import StateConnectionsEditorView
from logging import LoggingView
from state_editor import StateEditorView

from state_machine_tree import StateMachineTreeView
from library_tree import LibraryTreeView
#from state_editors_notebook import StateEditorsNotebookView
#from state_machines_notebook import StateMachinesNotebookView
#from main_window import MainWindowView
from menu_bar import MenuBarView
from tool_bar import ToolBarView