# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yaml_transmission.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yaml_transmission.proto',
  package='awesome_tool',
  serialized_pb=_b('\n\x17yaml_transmission.proto\x12\x0c\x61wesome_tool\"a\n\x05\x46iles\x12\'\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x18.awesome_tool.Files.File\x1a/\n\x04\x46ile\x12\x11\n\tfile_path\x18\x01 \x02(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FILES_FILE = _descriptor.Descriptor(
  name='File',
  full_name='awesome_tool.Files.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_path', full_name='awesome_tool.Files.File.file_path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_content', full_name='awesome_tool.Files.File.file_content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=138,
)

_FILES = _descriptor.Descriptor(
  name='Files',
  full_name='awesome_tool.Files',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='awesome_tool.Files.files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FILES_FILE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=138,
)

_FILES_FILE.containing_type = _FILES
_FILES.fields_by_name['files'].message_type = _FILES_FILE
DESCRIPTOR.message_types_by_name['Files'] = _FILES

Files = _reflection.GeneratedProtocolMessageType('Files', (_message.Message,), dict(

  File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
    DESCRIPTOR = _FILES_FILE,
    __module__ = 'yaml_transmission_pb2'
    # @@protoc_insertion_point(class_scope:awesome_tool.Files.File)
    ))
  ,
  DESCRIPTOR = _FILES,
  __module__ = 'yaml_transmission_pb2'
  # @@protoc_insertion_point(class_scope:awesome_tool.Files)
  ))
_sym_db.RegisterMessage(Files)
_sym_db.RegisterMessage(Files.File)


# @@protoc_insertion_point(module_scope)
