name: rafcon
channels:
  - conda-forge
  - zegami
dependencies:
  - pygobject>=3.50
  - gtk4
  - gtksourceview5
  - python=3.12
  - pip>=20.1
  - pip:
    - psutil==5.*
    - pylint
    - gaphas>=5.1.2,<6.0.0
    - jsonconversion>=1.0.0
    - yaml_configuration>=0.2.5,<0.3.0
