name: rafcon
channels:
  - conda-forge
  - zegami
dependencies:
  - pygobject
  - gtk
  - python=3.7
  - pip:
    - psutil==5.*
    - pylint
    - git+https://github.com/gaphor/gaphas.git@2.1.2#egg=gaphas
    - git+https://github.com/DLR-RM/python-jsonconversion.git@1.0.1#egg=jsonconversion
    - git+https://github.com/DLR-RM/python-yaml-configuration.git@master#egg=yaml_configuration
    - https://files.pythonhosted.org/packages/e3/d6/52994712b7d985a58614233fb3c317abaa6a91525d0c5e9f1be93ace03f6/python-gtkmvc3-dlr-1.0.1.tar.gz#egg=python-gtkmvc3-dlr
