# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udp_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='udp_message.proto',
  package='awesome_tool',
  serialized_pb=_b('\n\x11udp_message.proto\x12\x0c\x61wesome_tool\"b\n\nUDPMessage\x12\x0f\n\x07sm_name\x18\x01 \x01(\t\x12\x0f\n\x07root_id\x18\x02 \x01(\t\x12\x0c\n\x04\x66lag\x18\x03 \x02(\t\x12\x0f\n\x07message\x18\x04 \x02(\t\x12\x13\n\x0b\x61\x63knowledge\x18\x05 \x02(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UDPMESSAGE = _descriptor.Descriptor(
  name='UDPMessage',
  full_name='awesome_tool.UDPMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sm_name', full_name='awesome_tool.UDPMessage.sm_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='root_id', full_name='awesome_tool.UDPMessage.root_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='awesome_tool.UDPMessage.flag', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='awesome_tool.UDPMessage.message', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acknowledge', full_name='awesome_tool.UDPMessage.acknowledge', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['UDPMessage'] = _UDPMESSAGE

UDPMessage = _reflection.GeneratedProtocolMessageType('UDPMessage', (_message.Message,), dict(
  DESCRIPTOR = _UDPMESSAGE,
  __module__ = 'udp_message_pb2'
  # @@protoc_insertion_point(class_scope:awesome_tool.UDPMessage)
  ))
_sym_db.RegisterMessage(UDPMessage)


# @@protoc_insertion_point(module_scope)
