#!/bin/bash

SYSTEM=$(uname -s)

if [ $SYSTEM = "Linux" ]; then 
    MACHINE=$(uname -m)
fi

if [ $MACHINE = "i686" ]; then 
    echo "$SYSTEM $MACHINE"
elif [ $MACHINE = "x86_64" ]; then 
    echo "$SYSTEM $MACHINE"
else
    echo "Error: Unsupported architecture: $SYSTEM $MACHINE"
    exit 0
fi


# 32 bit
if [ $MACHINE = "i686" ]; then

	export PATH=/home/f_soft/bin/sled11-x86-gcc4.x:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin

	export LD_LIBRARY_PATH=/usr/lib/gcc/i586-suse-linux/4.7
	export LD_LIBRARY_PATH=/volume/USERSTORE/brun_sb/libraries/python_libraries/32_bit/lib:/volume/USERSTORE/brun_sb/libraries/sys_libraries/32_bit/lib:$LD_LIBRARY_PATH

	source /volume/USERSTORE/lehn_pt/ros/indigo/setup.bash

	export PYTHONPATH=/volume/USERSTORE/brun_sb/libraries/python_libraries/32_bit:/volume/USERSTORE/brun_sb/libraries/python_libraries/32_bit/lib/python2.7/site-packages:/volume/USERSTORE/brun_sb/libraries/python_libraries/32_bit/lib/python2.7/site-packages/gtk-2.0:$PYTHONPATH

	export PYTHONPATH=/volume/USERSTORE/brun_sb/public/DFC/source:/volume/USERSTORE/brun_sb/public/DFC/source/test_scripts:$PYTHONPATH

	PATH=/volume/USERSTORE/brun_sb/libraries/python_libraries/32_bit/bin:$PATH

# 64 bit
elif [ $MACHINE = "x86_64" ]; then

	export PATH=/home/f_soft/bin/sled11-x86_64-gcc4.x:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin

	export LD_LIBRARY_PATH=/usr/lib/gcc/i586-suse-linux/4.7
	export LD_LIBRARY_PATH=/volume/USERSTORE/brun_sb/libraries/python_libraries/64_bit/lib:/volume/USERSTORE/brun_sb/libraries/sys_libraries/64_bit/lib:/volume/USERSTORE/brun_sb/libraries/sys_libraries/64_bit/lib64:$LD_LIBRARY_PATH

	source /volume/USERSTORE/lehn_pt/ros/indigo/setup.bash

	export PYTHONPATH=/volume/USERSTORE/brun_sb/libraries/python_libraries/64_bit:/volume/USERSTORE/brun_sb/libraries/python_libraries/64_bit/lib/python2.7/site-packages:/volume/USERSTORE/brun_sb/libraries/python_libraries/64_bit/lib/python2.7/site-packages/gtk-2.0:$PYTHONPATH
	export PYTHONPATH=/volume/USERSTORE/brun_sb/public/DFC/source:/volume/USERSTORE/brun_sb/public/DFC/source/test_scripts:$PYTHONPATH

	PATH=/volume/USERSTORE/brun_sb/libraries/python_libraries/64_bit/bin:$PATH

fi

