DEFAULT_FONT = "FontAwesome"
FONT_SIZE_SMALL = "10"
FONT_SIZE_NORMAL = "12"
FONT_SIZE_BIG = "14"

TEXT_COLOR = "#c2c3c4"

MAIN_WINDOW_BORDER_WIDTH = 3
BORDER_WIDTH = 5
BORDER_WIDTH_TEXTVIEW = 10
BUTTON_BORDER_WIDTH = 5
BUTTON_MIN_WIDTH = 90
BUTTON_MIN_HEIGHT = 30

PADDING = 5

ICON_SIZE_IN_PIXEL = 20

BUTTON_EXP = "f065"
BUTTON_NEW = "f016"
BUTTON_OPEN = "f115"
BUTTON_SAVE = "f0c7"
BUTTON_PROP = "f0ad"
BUTTON_REFR = "f021"
BUTTON_CLOSE = "f00d"
BUTTON_QUIT = "f08b"
BUTTON_CUT = "f0c4"
BUTTON_COPY = "f0c5"
BUTTON_PASTE = "f0ea"
BUTTON_ADD = "f067"
BUTTON_GROUP = "f090"
BUTTON_UNGR = "f08b"
BUTTON_DEL = "f1f8"
BUTTON_UNDO = "f0e2"
BUTTON_REDO = "f01e"
BUTTON_VIEW = "f06e"
BUTTON_START = "f04b"
BUTTON_PAUSE = "f04c"
BUTTON_STOP = "f04d"
BUTTON_STEPM = "f050"
BUTTON_STEP = "f051"
BUTTON_BACKW = "f048"
BUTTON_ABOUT = "f0a3"