DEFAULT_FONT = "FontAwesome"
FONT_SIZE_SMALL = "10"
FONT_SIZE_NORMAL = "12"
FONT_SIZE_BIG = "14"

TEXT_COLOR = "#c2c3c4"

BORDER_WIDTH = 5
BORDER_WIDTH_TEXTVIEW = 10

PADDING = 5

ICON_SIZE_IN_PIXEL = 25