DEFAULT_FONT = "FontAwesome"
FONT_SIZE_SMALL = "10"
FONT_SIZE_NORMAL = "12"
FONT_SIZE_BIG = "14"

TEXT_COLOR = "#c2c3c4"

MAIN_WINDOW_BORDER_WIDTH = 3
BORDER_WIDTH = 5
BORDER_WIDTH_TEXTVIEW = 10
BUTTON_BORDER_WIDTH = 5

PADDING = 5

ICON_SIZE_IN_PIXEL = 25

BUTTON_CLOSE = "f00d"